import{a as b,S as E,i}from"./assets/vendor-BK_rxH-O.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const w="51679229-dd2564c95deaf9a31a7294431",S="https://pixabay.com/api/",A=15,B={key:w,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:A};async function P(r,e=1){const n={...B,q:String(r||"").trim(),page:e},{data:s}=await b.get(S,{params:n});return s}const m=document.getElementById("gallery"),h=document.querySelector(".loader"),g=document.getElementById("load-more"),p=new E(".gallery a",{captionsData:"alt",captionDelay:200});function v({webformatURL:r,largeImageURL:e,tags:n,likes:s,views:t,comments:o,downloads:a}){return`
    <li class="card">
      <a href="${e}">
        <img class="card-img" src="${r}" alt="${n||"photo"}" loading="lazy" />
      </a>
      <ul class="meta">
        <li><span class="label">Likes</span> ${s??0}</li>
        <li><span class="label">Views</span> ${t??0}</li>
        <li><span class="label">Comments</span> ${o??0}</li>
        <li><span class="label">Downloads</span> ${a??0}</li>
      </ul>
    </li>`}function R(r){if(!Array.isArray(r)||r.length===0)return;const e=r.map(v).join("");m.insertAdjacentHTML("beforeend",e),p.refresh()}function x(){m.innerHTML="",p.refresh()}function M(){h.classList.remove("hidden")}function $(){h.classList.add("hidden")}function q(){g.classList.remove("hidden")}function l(){g.classList.add("hidden")}const _=15,C=document.querySelector(".form"),H=document.querySelector('[name="search-text"]'),d=document.getElementById("load-more");let y="",c=1,u=0,f=!1;C.addEventListener("submit",I);d.addEventListener("click",N);async function I(r){r.preventDefault();const e=H.value.trim();if(!e){i.warning({title:"Warning",message:"Please enter a search word",position:"topRight",maxWidth:432});return}y=e,c=1,u=0,l(),x(),await L({isNewSearch:!0})}async function N(){f||(c+=1,await L({isNewSearch:!1}))}async function L({isNewSearch:r}){try{f=!0,M(),d.disabled=!0;const e=await P(y,c),n=Array.isArray(e==null?void 0:e.hits)?e.hits:[];if(u=Number.isFinite(e==null?void 0:e.totalHits)?e.totalHits:0,n.length===0){l(),i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",maxWidth:432,backgroundColor:"#EF4040",messageColor:"#fff"});return}R(n),c*_>=u?(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",maxWidth:432})):q(),r||O()}catch(e){l(),i.error({title:"Error",message:(e==null?void 0:e.message)||"Something went wrong",position:"topRight",maxWidth:432})}finally{$(),d.disabled=!1,f=!1}}function O(){const r=document.querySelector(".gallery .card");if(!r)return;const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
